Adding docker file
liqidinc/k8s-device-plugin pull request #3
Opened 2021-06-07 19:26 UTC by schittumuru

2021-06-08 14:30 UTC, zachflower commented
Hey @kyle-co, would you take a look at this?

2021-06-08 20:55 UTC, kyle-co commented on Dockerfile
> +COPY go.sum .
I would put these in the same line. Like this 

`COPY go.mod go.sum ./`

2021-06-08 21:02 UTC, kyle-co commented on Dockerfile
> +COPY . .
Can you describe what the purpose of this directive is? I am unsure of what it is intended to do. Looks like you're copying `.` to `.`, which strikes me as a no-op. I might be missing some detail though.

2021-06-08 21:06 UTC, kyle-co commented on main/main.go
> +		fmt.Printf(" -interval=value -deviceRootPath=devicepath -deviceName=name")
I would use just `fmt.Print` here, and not `fmt.Printf` -- this probably will trip a linter, since this func should take multiple variables.

2021-06-08 21:13 UTC, kyle-co commented on main/main.go
Below this commit (GitHub won't let me comment on other commits outside this PR), I see this:

`glog.Info("Polling interval is for every %v seconds!", pollingInterval)`

I think you want to use 

`glog.Infof()` like you would `fmt.Printf`, since it takes params besides the string. I think it will just concatenate the time on the end, and not inserted into the formatting like you're hoping. 

As well, I would error check `manager := dpm.NewManager(&lister)`.

2021-06-08 21:14 UTC, kyle-co requested changes
Just some small changes requested. Let me know if there are questions or if I missed some details.

2021-06-09 17:45 UTC, schittumuru commented on Dockerfile
> +COPY go.sum .
yes you are right it was mistake. Now I removed these copy statements as these are not needed any more.

2021-06-09 17:46 UTC, schittumuru commented on Dockerfile
> +COPY . .
This copy command is needed to copy source files into working directory of docker build .

2021-06-09 17:46 UTC, schittumuru commented on main/main.go
> +		fmt.Printf(" -interval=value -deviceRootPath=devicepath -deviceName=name")
Done.

2021-06-09 17:48 UTC, schittumuru commented on main/main.go
Fixed the code for glog.Infof().
Coming to manger:=dpm.NewManager(&lister) this invocation is not returning any error response. And this the framework code so I did not do any modifications.

2021-06-11 16:37 UTC, zachflower commented
If #4 contains all the relevant changes, I'm fine closing this and moving the discussion over there.

2021-06-11 16:37 UTC, closed without merging