Feature/liqcnbe 445
liqidinc/k8s-device-plugin pull request #4
Opened 2021-06-08 18:21 UTC by schittumuru

Contains changes related to github workflow action configuration to build, test, create docker image and push to github registry.

2021-06-08 21:15 UTC, kyle-co commented on Dockerfile
> +COPY go.sum .
Can we combine these into one line?

2021-06-08 21:16 UTC, kyle-co commented on main/main.go
> +		fmt.Printf(" -interval=value -deviceRootPath=devicepath -deviceName=name")
This was addressed in the other PR, but I think line 26 will fail a linter (and may even throw a runtime error) since `fmt.Printf` expects arguments passed into the formatting string.

2021-06-08 21:17 UTC, kyle-co requested changes
Small changes requested.

2021-06-09 17:41 UTC, schittumuru commented on Dockerfile
> +COPY go.sum .
It was mistake from my side these are not needed anymore, as the purpose is solved by the command "COPY . ."

2021-06-09 17:43 UTC, schittumuru commented on Dockerfile
> +COPY . .
This command is needed to copy the source files into working directory of the staging build.

2021-06-09 17:43 UTC, schittumuru commented on main/main.go
> +		fmt.Printf(" -interval=value -deviceRootPath=devicepath -deviceName=name")
Done.

2021-06-09 17:49 UTC, schittumuru commented
Please review again and let me know if you still some comments to share. Thanks

2021-06-14 16:41 UTC, kyle-co approved these changes

2021-06-14 21:12 UTC, merged